[package]
name = "catalyst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.34"
libc = "0.2.132"
mio = "0.8.4"
tokio = { version = "1.21.0", features = ["rt", "net", "sync", "io-util"] }
tokio-fd = "0.3.0"
errno = "0.2.8"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
bytes = "1.2.1"
byteorder = "1.4.3"
pnet = "0.31.0"

[build-dependencies]
cc = "1.0.73"
