[package]
name = "catalyst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.34"
libc = "0.2.132"
tokio = { version = "1.21.0", features = ["rt", "rt-multi-thread", "net", "sync", "io-util", "macros"] }
tokio-fd = "0.3.0"
errno = "0.2.8"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
bytes = "1.2.1"
byteorder = "1.4.3"
ipnet = "2.5.0"
ioctl-sys = "0.8.0"
smoltcp = "0.8.1"
