[package]
name = "boltconn-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcgen = "0.10.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
structopt = "0.3.26"
