interface: auto
inbound:
  http: 7890
  socks5: 7891

web-controller:
  api-addr: 18086
  api-key: null

dns:
  bootstrap:
    - 1.1.1.1
  nameserver:
    - doh, dns.adguard.com
    - udp, 8.8.8.8

proxy-local:
  lan-http:
    type: http
    server: 172.17.10.1
    port: 8080
    auth: null
  lan-socks:
    type: socks5
    server: 192.168.1.1
    port: 1080
    auth: null

proxy-provider:
  US:
    type: file
    path: ./Remote/US.yaml

proxy-chain:
  local-chain:
    chains:
      - lan-http
      - lan-socks

proxy-group:
  Relay:
    proxies:
      - lan-http
      - lan-socks
      - local-chain
      - DIRECT
    providers:
      - US
  US:
    providers:
      - US
  Default:
    proxies:
      - Relay
      - DIRECT

rule-providers:
  APPLE:
    type: file
    behavior: classical
    path: ./Rules/Apple
  TELEGRAM:
    type: file
    behavior: classical
    path: ./Rules/Telegram

modules:
  Google:
    type: file
    path: ./Module/google.yaml

rules:
  - include: ./Rules/local.yaml
  - module: Google
  - RULE-SET, APPLE, US
  - RULE-SET, TELEGRAM, lan-socks
  - FALLBACK, Default

interception:
  - module: Google
  - name: local-capture
    filters:
      - DOMAIN-SUFFIX, wikipedia.org
    actions:
      - capture
