rule-local:
  - DOMAIN-SUFFIX, google.com, Relay

intercept-rule:
  - DOMAIN-SUFFIX, google.com
  - DOMAIN-SUFFIX, google.co.uk

rewrite:
  - url, ^https://www.google.co.uk(.*), 302, https://www.google.com
  - url, ^https://careers.google.com, 404
#  - header-req, ^https://(.*)google.com, set, User-Agent, wget/22.04
#  - header-resp, ^https://mail.google.com, set, Set-Cookie, 123455678