rule-providers:
  GOOGLE:
    type: file
    behavior: domain
    path: ../Rules/Google

rules:
  - include: ./google-rules.yaml
  - RULE-SET, GOOGLE, Relay

interception:
  - name: google-redirects
    filters:
      - DOMAIN-SUFFIX, google.co.uk
    actions:
      - url, ^https://www.google.co.uk(.*), 302, https://www.google.com
