[package]
name = "boltconn"
version = "0.2.1"
edition = "2021"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7.20"
anyhow = "1.0.66"
arrayref = "0.3.6"
async-trait = "0.1.58"
axum = "0.6.1"
base64 = "0.21.0"
boltapi = { path = "../boltapi" }
boringtun = "0.5.2"
byteorder = "1.4.3"
bytes = "1.2.1"
chrono = { version = "0.4.23", default-features = false, features = ["clock", "std"] }
dashmap = "5.4.0"
fast-socks5 = "0.8.1"
fastrand = "1.8.0"
flume = "0.10.14"
futures = "0.3.25"
http = "0.2.8"
httparse = "1.8.0"
hyper = { version = "0.14.23", features = ["stream", "server", "client", "http1", "http2"] }
ioctl-sys = "0.8.0"
ipnet = "2.5.1"
ip_network = "0.4.1"
ip_network_table = "0.2.0"
is-root = "0.1.2"
libc = "0.2.137"
linked-hash-map = {version = "0.5.6" ,features = ["serde_impl"]}
radix_trie = "0.2.1"
rcgen = { version = "0.10.0", features = ["pem", "x509-parser"] }
regex = "1.7.0"
reqwest = "0.11.13"
rustls-pemfile = "1.0.1"
scopeguard = "1.1.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.14"
sha2 = "0.10.6"
shadowsocks = "1.15.0"
socket2 = "0.5.1"
smoltcp = "0.9.0"
structopt = "0.3.26"
thiserror = "1.0.37"
tokio = { version = "1.25.0", features = ["rt", "rt-multi-thread", "net", "sync", "io-util", "macros", "signal", "time"] }
tokio-rustls = { version = "0.23.4", features = ["dangerous_configuration"] }
tokio-tungstenite = "0.18.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "std", "fmt"] }
trust-dns-proto = "0.22.0"
trust-dns-resolver = { version = "0.22.0", features = ['dns-over-rustls', 'dns-over-https-rustls', 'dns-over-https', 'dns-over-tls'] }
webpki-roots = "0.22.5"
x25519-dalek = "2.0.0-pre.1"
[target.'cfg(target_os = "linux")'.dependencies]
netlink-sys = "0.8.3"
netlink-packet-sock-diag = "0.4.0"
