[package]
name = "boltconn"
version = "0.1.6"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boltapi = { path = "../boltapi" }
thiserror = "1.0.37"
anyhow = "1.0.66"
async-trait = "0.1.58"
libc = "0.2.137"
tokio = { version = "1.22.0", features = ["rt", "rt-multi-thread", "net", "sync", "io-util", "macros", "signal"] }
tokio-rustls = "0.23.4"
rustls-pemfile = "1.0.1"
webpki-roots = "0.22.5"
errno = "0.2.8"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "std", "fmt"] }
bytes = "1.2.1"
byteorder = "1.4.3"
scopeguard = "1.1.0"
ipnet = "2.5.1"
ioctl-sys = "0.8.0"
smoltcp = "0.8.1"
dashmap = "5.4.0"
arrayref = "0.3.6"
libproc = "0.12.0"
trust-dns-proto = "0.22.0"
trust-dns-resolver = "0.22.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_yaml = "0.9.14"
serde_json = "1.0.89"
chrono = { version = "0.4.23", default-features = false, features = ["clock", "std"] }
http = "0.2.8"
hyper = { version = "0.14.23", features = ["stream", "server", "client", "http1", "http2"] }
httparse = "1.8.0"
fast-socks5 = "0.8.1"
shadowsocks = "1.14.2"
axum = "0.6.0"
radix_trie = "0.2.1"
aho-corasick = "0.7.20"
reqwest = "0.11.13"
fastrand = "1.8.0"
nix = "0.26.1"
[target.'cfg(target_os = "linux")'.dependencies]
netlink-sys = "0.8.3"
netlink-packet-sock-diag = "0.4.0"
