proxies:
  - {name: Redmond, server: microsoft.com, port: 12345, type: ss, cipher: aes-256-gcm, password: Sydney, udp: true}
  - {name: Mountain View, server: google.com, port: 23456, type: ss, cipher: aes-256-gcm, password: Bard, udp: true}